version: '3.7'

services:
  api-db:
    build:
      context: ./services/api-db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './services/api-db:/usr/src/db'

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - './services/api:/usr/src/app'
    depends_on:
      - api-db